name: Elixir CI

env:
  ELIXIR_VERSION: 1.13.2
  OTP_VERSION: 24.2

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["24", "25"]
        elixir: ["1.11", "1.14"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: deps
          key: deps-${{ env.MIX_ENV }}-v${{ matrix.elixir }}-otp-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.MIX_ENV }}-v${{ matrix.elixir }}-otp-${{ matrix.otp }}-

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: plts-${{ env.MIX_ENV }}-v${{ matrix.elixir }}-otp-${{ matrix.otp }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            plts-v${{ matrix.elixir }}-otp-${{ matrix.otp }}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test --trace

      - name: Check Typespec
        run: mix dialyzer --halt-exit-status

      - name: Build Code Coverage Report
        run: mix coveralls.json

      - name: Upload Code Coverage Report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover/excoveralls.json
