name: Elixir CI

env:
  ELIXIR_VERSION: 1.9.4
  OTP_VERSION: 22.2

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }} # Define the elixir version [required]
          otp-version: ${{ env.OTP_VERSION }} # Define the OTP version [required]

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: priv/plts
          key: plts-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ github.sha }}
          restore-keys: |
            plts-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-

      - name: Install Dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Tests
        run: mix test

      - name: Check Typespec
        run: mix dialyzer --halt-exit-status
